[profile.default]
src = "src"
out = "out"
solc_version = "0.8.29"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
libs = ["lib"]

remappings = [
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts-ccip/=lib/ccip/contracts/",
  "@account-abstraction/contracts/=lib/account-abstraction/contracts/",
]

viaIR= true

[rpc_endpoints]
apothem = "${APOTHEM_RPC_URL}"
xdc_mainnet = "${XDC_MAINNET_RPC_URL}"
xrplevm = "${XRPL_TESTNET_RPC_URL}"

[etherscan]
xdc_mainnet = { key = "${XDC_SCAN_API_KEY}", url = "${XDC_ETHERSCAN_VERIFIER_URL}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
